version: "3.7"
services:

  relay:
    build:
      context: ../
      dockerfile: ./basic/Dockerfile
    environment:
      PORT: 2700
      POSTGRESQL_DATABASE: postgres://nostr:nostr@postgres:5432/nostr?sslmode=disable
    depends_on:
      - postgres
        #condition: service_healthy
    ports:
      - 8008:2700
    command: "./basic/relayer-basic"
    networks:
      default:
        ipv4_address: 10.10.10.2

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: nostr
      POSTGRES_USER: nostr
      POSTGRES_PASSWORD: nostr
      POSTGRES_HOST_AUTH_METHOD: trust # allow all connections without a password. This is *not* recommended for prod
    ports:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nostr"] # database username here - nostr, should be changed if other user
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
    - ../postgresql.conf:/postgresql.conf
    command: postgres -c 'config_file=/postgresql.conf'
    networks:
      default:
        ipv4_address: 10.10.10.3

  datadog-agent:
    container_name: datadog-agent
    image: datadog/agent:latest
    environment:
      ## GLOBALS
    - DD_API_KEY=${DD_API_KEY}
    - DD_SITE=datadoghq.com
    - DD_HOSTNAME=GO_relay
    - DD_TAGS=env:nostr-sandbox owner:brian
    - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
    - DD_DOCKER_LABELS_AS_TAGS=true
    - DD_DOCKER_ENV_AS_TAGS=true
    - DD_SYSTEM_PROBE_ENABLED=true
    - DD_PROCESS_AGENT_ENABLED=true
    - DD_LOGS_ENABLED=true
    - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /proc/:/host/proc/:ro
    - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
    - /sys/kernel/debug:/sys/kernel/debug
    cap_add:
    - SYS_ADMIN
    - SYS_RESOURCE
    - SYS_PTRACE
    - NET_ADMIN
    - NET_BROADCAST
    - NET_RAW
    - IPC_LOCK
    - CHOWN
    security_opt:
    - apparmor:unconfined
    networks:
      nostr-ts-relay:
        ipv4_address: 10.10.10.3
        
networks:
  default:
    name: nostr-ts-relay
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/24
